data =[{
    "processor_type": "Intel Core i7",
    "processor_speed": "3.6 GHz",
    "ram": "16 GB,",
    "storage_type": "SSD",
    "storage_size": "512 GB",
    "graphics_card": "Nvidia GeForce RTX 3070",
    "display_size": "15.6 inches",
    "display_resolution": "1920x1080",
    "operating_system": "Windows 10 Home",
    "price": 400,
    "brand": "Dell",
    "specifications": ["16GB DDR4 RAM", "512GB SSD", "Nvidia GeForce RTX 3070"],
    "warranty_information": "2-year limited warranty",
    "customer_reviews": [4.5, 4.7, 4.8]
},
{
    "processor_type": "AMD Ryzen 5",
    "processor_speed": "3.8 GHz",
    "ram": "8 GB",
    "storage_type": "HDD",
    "storage_size": "1 TB",
    "graphics_card": "AMD Radeon RX 550",
    "display_size": "14 inches",
    "display_resolution": "1366x768",
    "operating_system": "Windows 10 Pro",
    "price": 799.99,
    "brand": "Acer",
    "specifications": ["8GB DDR4 RAM", "1TB HDD", "AMD Radeon RX 550"],
    "warranty_information": "1-year limited warranty",
    "customer_reviews": [4.3, 4.6, 4.7]
},
{
    "processor_type": "Intel Core i5",
    "processor_speed": "3.0 GHz",
    "ram": "8 GB",
    "storage_type": "SSD",
    "storage_size": "256 GB",
    "graphics_card": "Intel UHD Graphics 620",
    "display_size": "13.3 inches",
    "display_resolution": "1920x1080",
    "operating_system": "MacOS",
    "price": 1299.99,
    "brand": "Apple",
    "specifications": ["8GB DDR3 RAM", "256GB SSD", "Intel UHD Graphics 620"],
    "warranty_information": "1-year limited warranty",
    "customer_reviews": [4.8, 4.9, 5.0]
}
]